config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :service_providers
  resources :service_types

  root 'service_providers#index'

end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
  has_and_belongs_to_many :service_types
  validates_presence_of :name, :address, :city, :state, :zipcode, :latitude, :longitude, :phone
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  has_and_belongs_to_many :service_providers
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable#, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]

  # GET /service_providers
  # GET /service_providers.json
  def index
    @service_providers = ServiceProvider.all
  end

  # GET /service_providers/1
  # GET /service_providers/1.json
  def show
  end

  # GET /service_providers/new
  def new
    @service_provider = ServiceProvider.new
  end

  # GET /service_providers/1/edit
  def edit
  end

  # POST /service_providers
  # POST /service_providers.json
  def create
    @service_provider = ServiceProvider.new(service_provider_params)

    respond_to do |format|
      if @service_provider.save
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully created.' }
        format.json { render :show, status: :created, location: @service_provider }
      else
        format.html { render :new }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_providers/1
  # PATCH/PUT /service_providers/1.json
  def update
    respond_to do |format|
      if @service_provider.update(service_provider_params)
        format.html { redirect_to @service_provider, notice: 'Service provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_provider }
      else
        format.html { render :edit }
        format.json { render json: @service_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_providers/1
  # DELETE /service_providers/1.json
  def destroy
    @service_provider.destroy
    respond_to do |format|
      format.html { redirect_to service_providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_provider_params
      params.require(:service_provider).permit(:name, :address, :phone, :city, :state, :zipcode, :latitude, :longitude, {:service_type_ids => []})
    end
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  before_action :set_service_type, only: [:show, :edit, :update, :destroy]

  # GET /service_types
  # GET /service_types.json
  def index
    @service_types = ServiceType.all
  end

  # GET /service_types/1
  # GET /service_types/1.json
  def show
  end

  # GET /service_types/new
  def new
    @service_type = ServiceType.new
  end

  # GET /service_types/1/edit
  def edit
  end

  # POST /service_types
  # POST /service_types.json
  def create
    @service_type = ServiceType.new(service_type_params)

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to @service_type, notice: 'Service type was successfully created.' }
        format.json { render :show, status: :created, location: @service_type }
      else
        format.html { render :new }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_types/1
  # PATCH/PUT /service_types/1.json
  def update
    respond_to do |format|
      if @service_type.update(service_type_params)
        format.html { redirect_to @service_type, notice: 'Service type was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_type }
      else
        format.html { render :edit }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1
  # DELETE /service_types/1.json
  def destroy
    @service_type.destroy
    respond_to do |format|
      format.html { redirect_to service_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_type
      @service_type = ServiceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_type_params
      params.require(:service_type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HYServiceDirectory</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">HY Dir</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Providers", service_providers_path %></li>
          <li><%= link_to "Service Types", service_types_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <% if user_signed_in? %>
                  <%= current_user.email %>
              <% else %>
                  User
              <% end %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                  <li><%= link_to "Log In", new_user_session_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%=(flash[:notice] && 'success' or flash[:warning] && 'warning' or flash[:info] && 'info' or 'error')%>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
  <% end %>
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/service_providers/_form.html.erb
<%= simple_form_for @service_provider, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipcode %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.input :phone %>
  <%= hidden_field_tag "service_provider[service_type_ids][]", nil%>
  <%= f.association :service_types, as: :check_boxes %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                service_providers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/service_providers/edit.html.erb
<%- model_class = ServiceProvider -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_providers/index.html.erb
<%- model_class = ServiceProvider -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= link_to service_provider.name, service_provider_path(service_provider) %></td>
        <td><%= service_provider.address %></td>
        <td><%= service_provider.city %></td>
        <td><%= service_provider.state %></td>
        <td><%= service_provider.zipcode %></td>
        <td><%= service_provider.latitude %></td>
        <td><%= service_provider.longitude %></td>
        <td><%= service_provider.phone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_provider_path(service_provider), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_provider_path(service_provider),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_provider_path,
            :class => 'btn btn-primary' %>

app/views/service_providers/new.html.erb
<%- model_class = ServiceProvider -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_providers/show.html.erb
<%- model_class = ServiceProvider -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @service_provider.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @service_provider.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @service_provider.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @service_provider.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zipcode) %>:</strong></dt>
  <dd><%= @service_provider.zipcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @service_provider.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @service_provider.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @service_provider.phone %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              service_providers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_provider_path(@service_provider), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_provider_path(@service_provider),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/service_types/_form.html.erb
<%= simple_form_for @service_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                service_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<%- model_class = ServiceType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_types/index.html.erb
<%- model_class = ServiceType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @service_types.each do |service_type| %>
      <tr>
        <td><%= link_to service_type.name, service_type_path(service_type) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_service_type_path(service_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      service_type_path(service_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_service_type_path,
            :class => 'btn btn-primary' %>

app/views/service_types/new.html.erb
<%- model_class = ServiceType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/service_types/show.html.erb
<%- model_class = ServiceType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @service_type.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              service_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_type_path(@service_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_type_path(@service_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>